/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Antropofago;


import java.awt.*;
import java.util.ArrayList;

/**
 * @author Erik
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form Lienzo
     */
    public static ArrayList<Antropofago> antropofagos = new ArrayList<>();
    MAntropofago mAntropofago = new MAntropofago();

    ArrayList<Color> colores;

    public Lienzo() {
        initComponents();

        colores = new ArrayList<>();
        colores.add(Color.BLACK);
        colores.add(Color.BLUE);
        colores.add(Color.YELLOW);
        colores.add(Color.CYAN);
        colores.add(Color.DARK_GRAY);
        colores.add(Color.GREEN);
        colores.add(Color.LIGHT_GRAY);
        colores.add(Color.ORANGE);
        colores.add(Color.RED);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paint(Graphics g) {
        /* color del fondo*/
        g.setColor(new Color(246, 236, 236));
        /* tamaño del fondo*/
        g.fillRect(0, 0, getWidth(), getHeight());

        g.setColor(Color.DARK_GRAY);
        /**
         *  (X,Y,Ancho,Alto)
         * */

        numeroMisioneros(mAntropofago, g);
        g.fillRect(40,400,40,40);
        g.drawString("COCINERO",45,450);
         /* dibujando Antropofagos */
        for (int i = 0; i < antropofagos.size(); i++) {
            antropofagos.get(i).setGraphics(g);
            antropofagos.get(i).getGraphics().setColor(antropofagos.get(i).getColor());
            g.fillOval(antropofagos.get(i).getCordenadaX(),
                    antropofagos.get(i).getCordenadaY(),
                    30, 30);
        }
        cocinero.setGraphics(g);
    }

    public void numeroMisioneros(MAntropofago m, Graphics g) {
        int i;
        int j = 40;
        for (i = 0; i < m.getNumeroMisioneros(); i++) {
            g.fillRect(j, 375, 10, 10);
            j = j + 20;
        }
    }

    public void generarAntropofagos(int i) {
        antropofagos.add(new Antropofago(mAntropofago,
                0,
                this,
                null,
                10,// coordenada X
                300,// coordenada Y
                15,//delay
                colores.get((int) (Math.random() * colores.size()))
        ));

        antropofagos.get(i).start();

    }

    Thread generarAntropofagos = new Thread(() -> {
        int i = 0;
        while (true) {
            try {
                repaint();
                generarAntropofagos(i);
                Thread.sleep(3000);
                i++;
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    });

    Cocinero cocinero = new Cocinero(mAntropofago,
            0,
            this,
            null,
            450,// coordenada X
            370,// coordenada Y
            15,//delay
            Color.yellow);

    @Override
    public void run() {
        generarAntropofagos.start();
        cocinero.start();
    }
}
